on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        #if: github.event.schedule != '30 5 * * 1,3'
        run: echo "Execute this command and print current date $(date)"
      #- name: Every time
        #run: echo "This step will always run"
